# sphm: Spherical Regression by Scaled Mobius Link

This directory contains an R package for running the regression model with SvMF error distribution in the manuscript titled "Regression for spherical responses with linear and spherical covariates using a scaled link function" by Shogo Kato, Kassel L. Hingee, Janice L. Scealy, and Andrew T.A. Wood.

## Installation
This package can be installed by running

```
#install.packages("devtools")
devtools::install_github("kasselhingee/sphm")
```

## Reproducing Results in Manuscript
The two quarto documents (`.qmd` files) in `./vignettes/` reproduce the results for the midatlantic ridge and earthquake moment tensor regressions in the manuscript "Regression for spherical responses with linear and spherical covariates using a scaled link function".
For convenience `./vignettes/` also includes the `.pdf` reports generated by applying `quarto::quarto_render()` to each `.qmd`:

```
quarto::quarto_render("./vignettes/reproduce_midatlantic.qmd")
quarto::quarto_render("./vignettes/reproduce_earthquakes.qmd")
```

Currently all data required for these documents is also in `./vignettes/`.

## Included C++ Code
The package uses automatic differentiation via the [`CppAD`](https://github.com/coin-or/CppAD) C++ package, which is accessed using the [`scorematchingad`](https://cran.r-project.org/package=scorematchingad) R package on CRAN. To use automatic differentiation, functions must be written in C++ and use arguments that are special numeric classes for automatic differentiation. These functions are all in the `./src/` directory. The special classes are named by the `scorematchingad` package as `a1type` (real-valued number for automatic differentiation), `veca1` (vector of `a1type`), `mata1` (matrix of `a1type`).

