# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

meanlinkS2Scpp <- function(x, vec, p) {
    .Call('_sphm_meanlinkS2Scpp', PACKAGE = 'sphm', x, vec, p)
}

OmegaS2S_constraints_quad <- function(vec, p) {
    .Call('_sphm_OmegaS2S_constraints_quad', PACKAGE = 'sphm', vec, p)
}

#' Function for taping a general function. The function must have signature
#' `veca1 fun(const veca1 & independent, const veca2 & dynamic, const vecd & constvec, const matd & constmat)`.
#' Differentiation of `fun` will occur with respect to the independent arguments. The taping will keep of dependence on the dynamic arguments so that the value of the dynamic arguments can be changed in the tape. The constants (constvec and constmat) will be baked into the tape (to change these constants `tapefun` will have to be called again.
#' 
#' If some of the arguments are unwanted, I'm hoping I can write the function so that vectors of length zero are okay.
#'
#' @param fun A function with the correct signature.
#' @param ind_t The value of the independent argument to use for taping.
#' @param dyn_t The value of the dynamic argument to use for taping.
#' @param constants The value of the constants argument.
NULL

#' Tape using a pointer to a function created by RcppXPtrUtils::cppXPtr
#' [[Rcpp::Export]]
NULL

